# Generated by Django 3.1.2 on 2020-10-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('pentesting', 'Pentesting'), ('reversing', 'Reversing'), ('shell', 'Shell'), ('network', 'Network'), ('algorithm', 'Algorithm'), ('web', 'Web'), ('operating-system', 'Os'), ('design', 'Design')], default='pentesting', max_length=50),
        ),
    ]
